# Change the default theme to be use when building the site with Hugo
theme = "hugo-theme-relearn"
baseURL = "http://example.org/"
languageCode = "en-us"
title = "My New Hugo Site"

# For search functionality
[outputs]
home = [ "HTML", "RSS", "SEARCH"]
